A tuple is a collection of objects which is ordered and immutable
Tuples are sequences just like lists
The differences between tuples and lists are:
=> Tuples can't be changed like lists
=> Tuples use PARENTHESIS whereas lists use SQUARE BRACKETS

In [ ]:
#Create an empty tuple

my_tuple = ()
print(my_tuple)

()

In [ ]:
#Tuple having integers

my_tuple = (1,2,3)
print(my_tuple)

(1, 2, 3)

In [ ]:
#Tuple with mixed datatypes

my_tuple = (1, "Hello", 3.4)
print(my_tuple)

(1, 'Hello', 3.4)

In [ ]:
#Nested Tuple

my_tuple = ("mouse", [1,2,3], (4,5,6))
#Not: You can keep a list inside a tuple
print(my_tuple)

#List
#Note: You can also keep a tuple inside a list
my_list = ("jerry", [1,2,3], (4,5,6))
print(my_list)

('mouse', [1, 2, 3], (4, 5, 6))
('jerry', [1, 2, 3], (4, 5, 6))

In [ ]:
#Tuple packing
my_tuple = (3, 4.6, "catdog")
print(my_tuple)

#Now, we want to unpack it:
#Tuple unpacking
#The tuple must have the exact number of variables as we have here on the LHS
#a,b,c,d would give us an error
#no. of var on RHS while packing = no. of var on LHS while unpacking
a,b,c = my_tuple
# a,b,c,d = my_tuple
print(a)
print(b)
print(c)

my_tuple = 3, 4.6, "catdog"
print("tuple", my_tuple)
value = 1

(3, 4.6, 'catdog')
3
4.6
catdog
tuple (3, 4.6, 'catdog')

In [ ]:
#To create a tuple with only one item, you have to add a comma
#otherwise, Python will not recognize it as a tuple
#It will consider it as a value stored in a variable

my_tuple = (1,)
print(my_tuple)

(1,)

In [ ]:
#Accessing Elements of a Tuple
#Just like strings and list, tuples also have indexing

#Accessing tuple elements using indexing

my_tuple = ('a','b','c','d','e')

print("Length of tuple:", len(my_tuple)) #>>5
# a=0, b=1, c=2, d=3, e=4
# a=-5, b=-4, c=-3, d=-2, e=-1

print(my_tuple[0])
print(my_tuple[-1])
print(my_tuple[-5])
print(my_tuple[4])

Length of tuple: 5
a
e
a
e

In [ ]:
#Nested tuple

n_tuple = ("mouse", [1,2,3,4], (5,6,7))


#VALUE = INDEX
#m(value)=0(index), Similarly, o=1 u=2 s=3 e=4 
#m=-5 o=-4 u=-3 s=-2 e=-1

#VALUE = INDEX
#1(value)=0(index), Similarly, 2=1 3=3 4=4 
#1=-4 2=-3 3=-2 4=-1

#VALUE = INDEX
#5(value)=0(index), Similarly, 6=1 7=3 
#5=-3 6=-2 7=-1

#Nested index
print(n_tuple[0][3]) #>>'s'
print(n_tuple[1][1]) #>>'2'
print(n_tuple[-2][-2]) #>>'3'
print(n_tuple[2][1]) #>>'6'
print(n_tuple[-1][-2]) #>>'6'

s
2
3
6
6

In [ ]:
#Nested tuple

tup = (1,2,3,(10,20,30,(100,200,300),1000,2000),10000,20000)
# value = index
# 1 = 0
# 2 = 1
# 3 = 2

# 10 = 3,0
# 20 = 3,1
# 30 = 3,2

# 100 = 3,3,0
# 200 = 3,3,1
# 300 = 3,3,2

# 1000 = 3,4
# 2000 = 3,5

# 10000 = 4
# 20000 = 5

print(tup[0]) #-> 1
print(tup[1]) #-> 2
print(tup[2]) #-> 3
print(tup[3][0]) #-> 10
print(tup[3][1]) #-> 20
print(tup[3][2]) #-> 30
print(tup[3][3][0]) #-> 100
print(tup[3][3][1]) #-> 200
print(tup[3][3][2]) #-> 300
print(tup[3][4]) #-> 1000
print(tup[3][5]) #-> 2000
print(tup[4]) #-> 10000
print(tup[5]) #-> 20000

1
2
3
10
20
30
100
200
300
1000
2000
10000
20000

In [ ]:
#Similarly, for list: 

my_list = [1,2,3,[4,5,6,[7,8,9],10,11],12,13]

print(my_list[0]) #-> 1
print(my_list[1]) #-> 2
print(my_list[2]) #-> 3
print(my_list[3][0]) #-> 4
print(my_list[3][1]) #-> 5
print(my_list[3][2]) #-> 6
print(my_list[3][3][0]) #-> 7
print(my_list[3][3][1]) #-> 8
print(my_list[3][3][2]) #-> 9
print(my_list[3][4]) #-> 10
print(my_list[3][5]) #-> 11
print(my_list[4]) #-> 12
print(my_list[5]) #-> 13

print("================")
for i in range(len(my_list)):
    print (my_list[i])

1
2
3
4
5
6
7
8
9
10
11
12
13
================
1
2
3
[4, 5, 6, [7, 8, 9], 10, 11]
12
13

In [ ]:
#Mutability of Tuples

#Tuples are immutable. 
#ELements of a tuple can't be changed once assigned.
#If element itself is a mutable data typle like list, 
#then its nested items can be changed.

tup1 = ("a", "b", "c")
# tup1 = "A" ->this will give an error

In [ ]:
n_tuple = ("mouse", [1,2,3,4], (5,6,7))
n_tuple[1][1] = 10
print('1st output',n_tuple)
n_tuple[1].append(100)
print(n_tuple)
n_tuple[1].remove(1)
print(n_tuple)

# n_tuple[0][2] = 'z'
# n_tuple[2][1] = 13

1st output ('mouse', [1, 10, 3, 4], (5, 6, 7))
('mouse', [1, 10, 3, 4, 100], (5, 6, 7))
('mouse', [10, 3, 4, 100], (5, 6, 7))

In [ ]:
#Concatenation

tup1 = ("a", "b", "c")
tup2 = (1,2,3)
tup3 = tup1+tup2
print(tup3)
print(tup1+tup2)

('a', 'b', 'c', 1, 2, 3)
('a', 'b', 'c', 1, 2, 3)

In [ ]:
#OPTIONAL -> JUST FOR FUN 
import itertools #import iterative tools 

tuple1 = (1, 2, 3, 4, 5)
tuple2 = (3, 4, 5, 6, 7)

#Using itertools
tuple3 = tuple(item for item in itertools.chain(tuple1, tuple2))
print(tuple3)
# Output (1, 2, 3, 4, 5, 3, 4, 5, 6, 7)

(1, 2, 3, 4, 5, 3, 4, 5, 6, 7)

In [ ]:
#Deleting

tup = ("a","b","c")
# del tup[2] will give error
del tup #can delete entire tuple
# print(tup)

In [ ]:
#Advantages of Tuple

#faster than list since tuples are immutable
#tuple with immutable elements can be used as a key for dictionary. 
#With lists it's not possible
#tuple ensure write-protected for a data that doesn't change

In [ ]:
#Iterate using for loop

tup = (1,2,3)
for i in tup:
    print (i)
    
print("=========")

for i in range(len(tup)):
    print (tup[i])

1
2
3
=========
1
2
3

In [ ]:
#Iterate using while loop

tup = (1,2,3)
count = 0
while count<len(tup):
    print(tup[count])
    count+=1

counter = 0
while counter<len(tup):
    if counter==(len(tup)-1):
        print(tup[counter])
    else:
        print(tup[counter], end=",")
    
    counter+=1

1
2
3
1,2,3

In [ ]:
#Slicing a tuple

tuple1 = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# slice a tuple with start and end index number
print(tuple1[1:5])
# Output (1, 2, 3, 4)

# slice a tuple without start index
print(tuple1[:5])
# Output (0, 1, 2, 3, 4)

# slice a tuple without end index
print(tuple1[6:])
# Output (6, 7, 8, 9, 10)

# slice a tuple using negative indexing
print(tuple1[-5:-1])
# Output (6, 7, 8, 9)

(1, 2, 3, 4)
(0, 1, 2, 3, 4)
(6, 7, 8, 9, 10)
(6, 7, 8, 9)

In [ ]:
tuple1 = (10, 20, 30, 40, 30, 50, 60, 70, 80)

# get index of item 30
# the whole tuple is being searched
position = tuple1.index(30) #twice present, gives first occurrence
print(position)
# Output 2

# Limit the search locations using start and end
# search only from location 4 to 7
# start = 4 and end = 7
# get index of item 60
position = tuple1.index(60, 4, 7)
print(position)  
# Output 6

#BUT GIVING SMTH OUT OF INDEX = VALUE ERROR 
#e.g. position = tuple1.index(60, 10, 30)

2
6

In [ ]:
#IMPORTANT:
#A way to change smth in a tuple
#Convert the tuple to list, change it, then convert it back to tuple

tuple1 = (0, 1, 2, 3, 4, 5)

# converting tuple into a list
sample_list = list(tuple1)
print(sample_list)
# reomve 2nd item
sample_list.remove(2)

# converting list back into a tuple
tuple1 = tuple(sample_list)
print(tuple1)  
# Output (0, 1, 3, 4, 5)

[0, 1, 2, 3, 4, 5]
(0, 1, 3, 4, 5)

In [ ]:
nested_tuple = ((20, 40, 60), (10, 30, 50), "Python")

# access the first item of the third tuple
print("Nested Tuple:", nested_tuple[2][0])  # P

print("=========================================\n")
           
# iterate a nested tuple
for i in nested_tuple:
    print("tuple:", i, "elements")
    for j in i:
        print(j, end=" ")
    print("\n")
   
# BREAKING DOWN (TRACING FOR THIS SHOWN IN CLASS)

# FORMAT BELOW EXPLAINED:
# i = iteration number >>Output, j = j's iteration number >>Output

# i = 0, >>tuple: (20, 40, 60) elements, j = 0, >>20, j = 1, >>40, j = 2, >>60
# i = 1, >>tuple: (10, 30, 50) elements, j = 0, >>10, j = 1, >>30, j = 2, >>50
# i = 2, >>tuple: Python elements, 
#j = 0, >>P, j = 1, >>y, 
#j = 2, >>t, j = 3, >>h, 
#j = 4, >>o, j = 5, >>n

Nested Tuple: P
=========================================

tuple: (20, 40, 60) elements
20 40 60

tuple: (10, 30, 50) elements
10 30 50

tuple: Python elements
P y t h o n

In [ ]:
tuple1 = ('xyz', 'zee', 'abc')
# The Maximum value in a string tuple
print(max(tuple1))  
# Output zee

# The minimum value in a string tuple
print(min(tuple1))
# Output abc

tuple2 = (11, 22, 10, 4)
# The Maximum value in a integer tuple
print(max(tuple2))
# Output 22

# The minimum value in a integer tuple
print(min(tuple2))
# Output 4

zee
abc
22
4

In [ ]:
tuple1 = ('xyz', 'zee', 'abc', 'ZEE')
# The Maximum value in a string tuple
print(max(tuple1))  
# Output zee
#ascii value of lowercase z is higher than uppercase Z

zee

In [ ]:
tuple1 = ('xyz', 'xyzasd')
# The Maximum value in a string tuple
print(max(tuple1))  
# Output zara
#ascii value of lowercase z is higher than uppercase Z

xyzasd

In [ ]:
#EXAMPLES OF TUPLE

In [ ]:
#Reverse the tuple

tuple1 = (10, 20, 30, 40, 50)
tuple1 = tuple1[::-1]
print(tuple1)

#ALTERNATE
print("(", end='')
#NOTE: CURRENTLY TUPLE IS (50, 40, 30, 20, 10)
for i in range(len(tuple1)-1, -1, -1): #think from positive index view
    if (i == 0):
        print(tuple1[i], end=")")
    else:
        print(tuple1[i], end=", ")
print()
  
#ALTERNATE
print("(", end='')
#NOTE: CURRENTLY TUPLE IS (50, 40, 30, 20, 10)
for i in range(-1, -len(tuple1)-1, -1): #think from negative index view
    if (i == -len(tuple1)):
        print(tuple1[i], end=")")
    else:
        print(tuple1[i], end=", ")

(50, 40, 30, 20, 10)
(10, 20, 30, 40, 50)
(10, 20, 30, 40, 50)

Homework:

Exercise 1: 
Reverse the tuple

Given:
tuple1 = (10, 20, 30, 40, 50)

Expected output:
(50, 40, 30, 20, 10)

#=========================================================================================================

Exercise 2: 
Access value 20 from the tuple

Given:
tuple1 = ("Ironman", [10, 20, 30], (5, 15, 25))

Expected output:
20

#=========================================================================================================

Exercise 3: 
Create a tuple with single item 50

Expected output:
(50,)

#=========================================================================================================

Exercise 4: 
Unpack the tuple into 4 variables

Given:
tuple1 = (10, 20, 30, 40)

Expected output:
print(a) # should print 10 
print(b) # should print 20
print(c) # should print 30
print(d) # should print 40

#=========================================================================================================

Exercise 5: 
Swap two tuples in Python. 
Printing tuple1 should give the tuple2's output and vise versa.
You CANNOT do it like this: print("tuple1:", tuple2)

Given:
tuple1 = (11, 22)
tuple2 = (99, 88)

Expected output:
tuple1: (99, 88)
tuple2: (11, 22)

#=========================================================================================================

Exercise 6: 
Write a program to copy elements 44 and 55 from the following tuple into a new tuple.

Given:
tuple1 = (11, 22, 33, 44, 55, 66)

Expected output:
tuple2: (44, 55)

#=========================================================================================================

Exercise 7: 
Modify the tuple. 
Given is a nested tuple. 
Write a program to modify the first item (22) of a list inside a following tuple to 222

Given:
tuple1 = (11, [22, 33], 44, 55)

Expected output:
tuple1: (11, [222, 33], 44, 55)

#=========================================================================================================

Exercise 8: 
Sort a tuple of tuples by 2nd item

Given:
tuple1 = (('a', 23),('b', 37),('c', 11), ('d',29))

Expected output:
(('c', 11), ('a', 23), ('d', 29), ('b', 37))

#=========================================================================================================

Exercise 9: 
Counts the number of occurrences of item 50 from a tuple

Given:
tuple1 = (50, 10, 60, 70, 50)

Expected output:
2

#=========================================================================================================

Exercise 10: 
Check if all items in the tuple are the same

Given:
tuple1 = (45, 45, 45, 45)

Expected output:
True

#=========================================================================================================