Dictionary is a data structure to hold a collection of values in a single variable
Python dictionary represents a mapping between a key and a value.
In simple terms, it can store pairs of keys and values. 

Each key is linked to a specific value.
-> Can have any number of items with a unique key
-> Dynamic: don't have to specify ANY FIXED SIZE, can easily add/remove elements

A dictionary is MUTABLE (can change individual items)

Popularly known as map/hash table/associative arrays in other langs

Each item in the dictionary has a key:value pair

In [ ]:
#Creating Empty Dictionary

create_dict = {}
print(create_dict)

{}

In [ ]:
dictionary = {'Name': 'Bob', 'Profession':'Builder', 'Age':35}
print(dictionary)

#All items enclosed between curly braces seperated by commas
#Colon(:) used to seperate key from its value
#Keys are unique and can be immutable data type(strings/numbers/tuples)
#Values don't have to be unique & can be of any data type including dictionaries

{'Name': 'Bob', 'Profession': 'Builder', 'Age': 35}

In [ ]:
#Creating dictionary using dict()

#keys = immutable values = string, numbers/integers/float, tuple
#value = mutable/immutable = string, numbers/integers, tuple, list, float

#Integer keys
create_dict = dict( {1:['cat',12,12.3], 2:'dog', 3:'python'} )
print(create_dict)

#String keys
create_dict = dict( {'1':'cat', '2':'dog', '3':'python'} )
print(create_dict)

#Tuple keys
create_dict = dict( {(1,2):'cat', (3,4):'dog', (5,6):'python'} )
print(create_dict)

#List key (mutable) = Error
# create_dict = dict( {[1,2]:'cat', [3,4]:'dog', [5,6]:'python'} )
# print(create_dict)
#UNHASHABLE TYPE LIST AS LIST=MUTABLE

#Float datatype keys
create_dict = dict( {1.2:'cat', 2.1:'dog', 3.5:'python'} )
print(create_dict)

{1: ['cat', 12, 12.3], 2: 'dog', 3: 'python'}
{'1': 'cat', '2': 'dog', '3': 'python'}
{(1, 2): 'cat', (3, 4): 'dog', (5, 6): 'python'}
{1.2: 'cat', 2.1: 'dog', 3.5: 'python'}

In [ ]:
#Dictionary with mixed keys

create_dict = {'Courses':['CSE110','CSE111'], 
               1:{10,20,15}, 
               (1,2):'A', 
               2.1:1 }
print(create_dict)

{'Courses': ['CSE110', 'CSE111'], 1: {10, 20, 15}, (1, 2): 'A', 2.1: 1}

In [ ]:
#Nested Dictionary

create_dict = {'Course':'CSE110', 'highest':{'name':'Troy', 'mark':50}}
print(create_dict)

Troy
{'Course': 'CSE110', 'highest': {'name': 'Troy', 'mark': 50}}

In [ ]:
#ACCESSING
#Just like strings/lists, 
#can use square brackets but keys must be used instead of index
#KEYERROR IF KEY NOT FOUND

#Can use built-in function get(key,value)
#-> KEY: TO BE SEARCHED
#-> VALUE: OPTIONAL: If no value found, the set value will be returned. 
#If not set, will return "None".

#Keys must be any available key in the dictionary

capt = {'Portugal':'Ronaldo', 'Argentina':'Messi', 'Spain':'Ramos'}

#KEY : VALUE
#Portugal : RONALDO
#Argentina : MESSI
#SPAIN : RAMOS

print(capt['Portugal']) #Ronaldo
# print(capt[' Brazil']) #KeyError
#so get method returns smth; either none or set value
#square bracketing [] gives error if value not found
print(capt.get('Argentina')) #Messi 
print(capt.get('Argentina', 'Not found')) #Messi 
print(capt.get('Brazil')) #None as not a valid key
print(capt.get('Brazil','Not found')) 
#Not found returned (not None) if not valid key

Ronaldo
Messi
Messi
None
Not found

In [ ]:
#Dictionary inside a dictionary (nested)
#Use [][]

capt = {'A':'1', 'B':'2', 'C':{'D':'3', 'E':'4', 'F':'5'}, 'G':6}
print(capt['C']) #'D:''3', 'E':'4', 'F':'5'
print(capt['C']['E']) #'4'
print(capt['C']['F']) #'5'


capt_ = {'A':'1', 'B':'2', 'C':{'D':'3', 
                                'E':{'Z':'4', 'X':'10', 
                                     'Y':{'M':'11', 'N':'100'}, 
                                     'F':'5'}, 'G':6}}
print(capt_['C']['E']['Y']['N'])  #100

{'D': '3', 'E': '4', 'F': '5'}
4
5
100

In [ ]:
#Dictionaries are mutable/changeable
#Like lists, key:value can be changed easily

#change, add, delete

#Variable[Key] = value
#VARIABLE = EXISTING DICTIONARY NAME
#KEY = NEW/EXISTING KEY
#VALUE = NEW VALUE

capt_ = {'A':'1', 'B':'2', 'C':{'D':'3', 
                                'E':{'Z':'4', 'X':'10', 
                                              'Y':{'M':'11', 'N':'100'}, 
                                              'F':'5'}, 'G':6}}
print(capt_)
print(capt_['C']['E']['Y']['N'])  #100
print("=====================================================================================================")

#UPDATE/CHANGE
capt_['C']['E']['Y']['N'] = 200
print(capt_['C']['E']['Y']['N'])  #200
print(capt_)

#ADD NEW VALUE
capt_['Spain']='Casillas'
print(capt_)
print("=====================================================================================================")

capt_['C']['E']['Y']['Argentina']='Messi'
print(capt_)
print("=====================================================================================================")

{'A': '1', 'B': '2', 'C': {'D': '3', 'E': {'Z': '4', 'X': '10', 'Y': {'M': '11', 'N': '100'}, 'F': '5'}, 'G': 6}}
100
=====================================================================================================
200
{'A': '1', 'B': '2', 'C': {'D': '3', 'E': {'Z': '4', 'X': '10', 'Y': {'M': '11', 'N': 200}, 'F': '5'}, 'G': 6}}
{'A': '1', 'B': '2', 'C': {'D': '3', 'E': {'Z': '4', 'X': '10', 'Y': {'M': '11', 'N': 200}, 'F': '5'}, 'G': 6}, 'Spain': 'Casillas'}
=====================================================================================================
{'A': '1', 'B': '2', 'C': {'D': '3', 'E': {'Z': '4', 'X': '10', 'Y': {'M': '11', 'N': 200, 'Argentina': 'Messi'}, 'F': '5'}, 'G': 6}, 'Spain': 'Casillas'}
=====================================================================================================

In [ ]:
#Continue adding / updating elements using BUILT IN function

#update(dictionary)=>> 
#If key is present, updates. 
#Else, adds key:value pair

book = {'author':'Enid Blyton', 
        'novel':'Famous five', 
        'year':'1998'}
print(book)
print("=========================")

print("updates novel key")
book.update({'novel':'The Secret Seven'}) #updates novel key
print(book)
print("=========================")
book.update(novel='The Secret Seven') #updates novel key
print(book)
print("=========================")

print("adds series key")
book.update({'series':'Five goes on Adventure'}) #adds series key
print(book)
print("=========================")
book.update(series='Five goes on Adventure') #adds series key
print(book)
print("=========================")

{'author': 'Enid Blyton', 'novel': 'Famous five', 'year': '1998'}
=========================
updates novel key
{'author': 'Enid Blyton', 'novel': 'The Secret Seven', 'year': '1998'}
=========================
{'author': 'Enid Blyton', 'novel': 'The Secret Seven', 'year': '1998'}
=========================
adds series key
{'author': 'Enid Blyton', 'novel': 'The Secret Seven', 'year': '1998', 'series': 'Five goes on Adventure'}
=========================
{'author': 'Enid Blyton', 'novel': 'The Secret Seven', 'year': '1998', 'series': 'Five goes on Adventure'}
=========================

In [ ]:
#Clear

book = {'author':'Enid Blyton', 'novel':'Famous five', 'year':'1998'}
print(book)
book.clear()
print(book)

{'author': 'Enid Blyton', 'novel': 'Famous five', 'year': '1998'}
{}

In [ ]:
#Popitem

book = {'author':'Enid Blyton', 'novel':'Famous five', 'year':'1998'}
print(book)
remove = book.popitem() #removes last item
print(remove)
print(book)

{'author': 'Enid Blyton', 'novel': 'Famous five', 'year': '1998'}
('year', '1998')
{'author': 'Enid Blyton', 'novel': 'Famous five'}

In [ ]:
#Pop

book = {'author':'Enid Blyton', 'novel':'Famous five', 'year':'1998'}
print(book)
remove = book.pop('novel') #pop the key; don't give keys that don't exist 
print(remove)
print(book)

{'author': 'Enid Blyton', 'novel': 'Famous five', 'year': '1998'}
Famous five
{'author': 'Enid Blyton', 'year': '1998'}

In [ ]:
empty_diction = {}
empty_diction.popitem() #-> error=dictionary is empty

KeyError: 'popitem(): dictionary is empty'

In [ ]:
#Deleting

book = {'author':'Enid Blyton', 'novel':'Famous five', 'year':'1998'}
print(book)
del book['year'] #deletes specific key
print(book)
del book #deletes whole dictionary
# print(book)

{'author': 'Enid Blyton', 'novel': 'Famous five', 'year': '1998'}
{'author': 'Enid Blyton', 'novel': 'Famous five'}

In [ ]:
book = {'author':'Enid Blyton', 'novel':'Famous five', 'year':'1998'}

#Doesn't take any parameter.
#Returns a view obj that contains a list of all the keys
list_keys = book.keys()
print(list_keys)

#Doesn't take any parameter.
#Returns a view obj that contains a list of all the values
list_values = book.values()
print(list_values)

#Doesn't take any parameter.
#Returns a view obj that contains 
#a list of all the key:value pairs in TUPLE form
list_items_tuple = book.items()
print(list_items_tuple)

# [('author', 'Enid Blyton'), ('novel', 'Famous five'), ('year', '1998')]

dict_keys(['author', 'novel', 'year'])
dict_values(['Enid Blyton', 'Famous five', '1998'])
dict_items([('author', 'Enid Blyton'), ('novel', 'Famous five'), ('year', '1998')])

In [ ]:
#IMPORTANT

book = {'author':'Enid Blyton', 
        'novel':'Famous five', 
        'year':'1998'}

#iterate over keys method 1:
for i in book:
    print(i)

print("=========================")
    
#iterate over keys method 2:
# ['author', 'novel', 'year'] = x = book.keys()
for key in book.keys(): 
    #list of all the keys er upor iterating
    print(key)
    
print("=========================")

#iterate over values 
for value in book.values(): #list of all the values er upor iterating
    print(value)

# for value in book: #Trick question, value here is actually the count. 
# NOT value of key.
#     print(value)

print("=========================")

#iterate over key:value
for key,value in book.items(): #iterating key, value simultaneously
    print(key + ' is ' + value)

print("=========================")

#iterate over key:value
for key in book:
    print(key, 'is', book[key])

author
novel
year
=========================
author
novel
year
=========================
Enid Blyton
Famous five
1998
=========================
author is Enid Blyton
novel is Famous five
year is 1998
=========================
author is Enid Blyton
novel is Famous five
year is 1998

In [ ]:
#built-in functions (len, max, min, sorted)

book = {'author':'Enid Blyton', 
        'novel':'Famous five', 
        'year':'1998', 
        'ZEE':'zee'}

print(len(book))
print(max(book.keys())) #y ascii value
print(max(book.values()))#F ascii value
print(min(book.keys()))
print(min(book.values()))
print(sorted(book.keys())) #according to ascii (ascending)
print(sorted(book.values())) #according to ascii (ascending)

4
year
zee
ZEE
1998
['ZEE', 'author', 'novel', 'year']
['1998', 'Enid Blyton', 'Famous five', 'zee']

In [ ]:
# setdefault() method default value can be assigned to a key in the dictionary. 
# In case the key doesn’t exist already, 
# then the key will be inserted into the dictionary, 
# and the value becomes the default value, 
# OTHERWISE, None will be inserted if a value is not mentioned.

# dictionary.setdefault(key, value)
# key doesn't exist, insert key, value=given
# key exists, doesn't change value

# dictionary.setdefault(key) 
# key doesn't exist, insert key, value=None 
# key exists, doesn't change value

person_details = {"name": "Jessa", "country": "USA", "telephone": 1178}

# set default value if key doesn't exists
person_details.setdefault('state', 'Texas')

# key doesn't exists and value not mentioned. default None
person_details.setdefault("zip")

# key exists and value mentioned. doesn't  change value
person_details.setdefault('country', 'Canada')

# key exists and value mentioned. doesn't  change value
person_details.setdefault('country')

# Display dictionary
for key, value in person_details.items():
    print(key, ':', value)

name : Jessa
country : USA
telephone : 1178
state : Texas
zip : None

In [ ]:
#in operator
person = {'name': 'Jessa', 'country': 'USA', 'telephone': 1178}

# Get the list of keys and check if 'country' key is present
key_name = 'country'
if key_name in person.keys():
    print("country name is", person[key_name])
else:
    print("Key not found")
# Output country name is USA

country name is USA

In [ ]:
#JOIN 2 dictionaries
# the dictionary to be added will be passed 
# as the argument to the update() method 
# and the updated dictionary will have items of both the dictionaries.

dict1 = {'Jessa': 70, 'Arul': 80, 'Emma': 55}
dict2 = {'Kelly': 68, 'Harry': 50, 'Olivia': 66}

# copy second dictionary into first dictionary
dict1.update(dict2)
# printing the updated dictionary
print(dict1)

#ALTERNATE

dict3 = {**dict1, **dict2}
print(dict3)

{'Jessa': 70, 'Arul': 80, 'Emma': 55, 'Kelly': 68, 'Harry': 50, 'Olivia': 66}
{'Jessa': 70, 'Arul': 80, 'Emma': 55, 'Kelly': 68, 'Harry': 50, 'Olivia': 66}

In [ ]:
#What happens if the second dictionary has a key 
#that already exists in the first dictionary when joining?

dict1 = {'Jessa': 70, 'Arul': 80, 'Emma': 55}
dict2 = {'Kelly': 68, 'Harry': 50, 'Emma': 66}

# join two dictionaries with some common items
dict1.update(dict2)
# printing the updated dictionary
print(dict1)
print(dict1['Emma'])

#ALTERNATE

dict3 = {**dict1, **dict2}
print(dict3)
print(dict3['Emma'])

#Is the below possible?

dict4 = dict1 + dict2
print(dict4)

{'Jessa': 70, 'Arul': 80, 'Emma': 66, 'Kelly': 68, 'Harry': 50}
66
{'Jessa': 70, 'Arul': 80, 'Emma': 66, 'Kelly': 68, 'Harry': 50}
66

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [ ]:
dict1 = {'Jessa': 70, 'Emma': 55}

# Copy dictionary using copy() method
dict2 = dict1.copy()
# printing the new  dictionary
print(dict2)
# output {'Jessa': 70, 'Emma': 55}

# Copy dictionary using dict() 
dict3 = dict(dict1)
print(dict3)
# output {'Jessa': 70, 'Emma': 55}

# Copy dictionary using the output of items() methods
dict4 = dict(dict1.items())
print(dict4)
# output {'Jessa': 70, 'Emma': 55}

# Copy dictionary using the = operator 
dict1 = {'Jessa': 70, 'Emma': 55}

# Copy dictionary using assignment = operator
dict2 = dict1

# modify dict2
dict2.update({'Jessa': 90})
print(dict2)
# Output {'Jessa': 90, 'Emma': 55}

print(dict1)
# Output {'Jessa': 90, 'Emma': 55}

{'Jessa': 70, 'Emma': 55}
{'Jessa': 70, 'Emma': 55}
{'Jessa': 70, 'Emma': 55}
{'Jessa': 90, 'Emma': 55}
{'Jessa': 90, 'Emma': 55}

In [ ]:
#Delete a list of keys from a dictionary

sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"
}
# Keys to remove
keys = ["name", "salary"]

for k in keys:
    sample_dict.pop(k)
print(sample_dict)

{'age': 25, 'city': 'New york'}

In [1]:
dict1 = {'Jessa': 70, 'Emma': 55}

dict2 = dict1

dict2.update({'Jessa': 90})
print(dict2)

print(dict1)

{'Jessa': 90, 'Emma': 55}
{'Jessa': 90, 'Emma': 55}

In [ ]:
#How to unpack nested tuple
#Output format: 
#The Silent Patient won the 'Best Mystery & Thriller' category with 68821 votes

book_info = (("Best Mystery & Thriller","The Silent Patient",68821),
             ("Best Horror","The Institute",75717),
             ("Best History & Biography","The five",31783 ),
             ("Best Fiction","The Testaments",98291))
for i in book_info:
    print("{} won the '{}' category with {} votes".format(i[1],i[0],int(i[2])))

In [ ]:
#Dictionary er certain jaygay, when not nested, kibhabe dhukabo? 

#Answer: you don't have to. As it is already unordered.

Homework:
    
Exercise 1: 
Convert two lists into a dictionary.
Below are the two lists. 
Write a Python program to convert them into a dictionary in a way that 
item from list1 is the key and item from list2 is the value

Given: 
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]

Expected output: 
{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

#=========================================================================================================

Exercise 2: 
Merge two Python dictionaries into one

Given:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 3000}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

Expected output: 
{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

#=========================================================================================================

Exercise 3: 
Print the value of key ‘history’ from the below dict

Given:
sampleDict = {
    "class": {
        "student": {
            "name": "Mike",
            "marks": {
                "physics": 70,
                "history": 80
            }
        }
    }
}

Expected output: 
{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

#=========================================================================================================

Exercise 4: 
Initialize dictionary with default values

Given: 
employees = ['Kelly', 'Emma']
defaults = {"designation": 'Developer', "salary": 8000}

Expected output: 
{'Kelly': {'designation': 'Developer', 'salary': 8000}, 'Emma': {'designation': 'Developer', 'salary': 8000}}

#=========================================================================================================

Exercise 5: 
Create a dictionary by extracting the keys from a given dictionary
Write a Python program to create a new dictionary by extracting the mentioned keys from the below dictionary

Given: 
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"}

#keys to extract
keys = ["name", "salary"]

Expected output: 
{'name': 'Kelly', 'salary': 8000}

#=========================================================================================================

Exercise 6: Delete a list of keys from a dictionary

Given: 
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"
}

#keys to remove
keys = ["name", "salary"]

Expected output: 
{'city': 'New york', 'age': 25}

#=========================================================================================================

Exercise 7: 
Check if a value exists in a dictionary. 
Write a Python program to check if value 200 exists in the following dictionary.

Given: 
sample_dict = {'a': 100, 'b': 200, 'c': 300}

Expected output: 
200 present in a dict

#=========================================================================================================

Exercise 8: 
Rename key of a dictionary.
Write a program to rename a key city to a location in the following dictionary.

Given: 
sample_dict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}

Expected output: 
{'name': 'Kelly', 'age': 25, 'salary': 8000, 'location': 'New york'}

#=========================================================================================================

Exercise 9: 
Get the key of a minimum value from the following dictionary

Given: 
sample_dict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}

Expected output: 
Math

#=========================================================================================================

Exercise 10: 
Change value of a key in a nested dictionary.
Write a Python program to change Brad’s salary to 8500 in the following dictionary.

Given: 
sample_dict = {
    'emp1': {'name': 'Jhon', 'salary': 7500},
    'emp2': {'name': 'Emma', 'salary': 8000},
    'emp3': {'name': 'Brad', 'salary': 500}
}

Expected output: 
{
   'emp1': {'name': 'Jhon', 'salary': 7500},
   'emp2': {'name': 'Emma', 'salary': 8000},
   'emp3': {'name': 'Brad', 'salary': 8500}
}

#=========================================================================================================